package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/hello/dao"
	generatedModel "github.com/hello/graph/model"
	"github.com/hello/models"
)

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input generatedModel.CreateEventInput) (*models.Event, error) {
	panic(fmt.Errorf("not implemented: CreateEvent - createEvent"))
}

// GetEvents is the resolver for the getEvents field.
func (r *queryResolver) GetEvents(ctx context.Context) ([]*models.Event, error) {
	events, err := dao.GetEvents(10, 0)
	fmt.Println("events: ---------->", events)
	if err != nil {
		return nil, err
	}
	var res []*models.Event
	for i := range events {
		res = append(res, &events[i])
	}
	return res, err
}

// GetEventByID is the resolver for the getEventById field.
func (r *queryResolver) GetEventByID(ctx context.Context, id string) (*models.Event, error) {
	event, err := dao.GetEventById(id)
	fmt.Print("event: ---------->", event)
	if err != nil {
		return nil, err
	}
	return &event, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
