package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/hello/dao"
	generatedModel "github.com/hello/graph/model"
	"github.com/hello/models"
)

// Payload is the resolver for the payload field.
func (r *eventResolver) Payload(ctx context.Context, obj *models.Event) (*string, error) {
	panic(fmt.Errorf("not implemented: Payload - payload"))
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input generatedModel.CreateEventInput) (*models.Event, error) {
	panic(fmt.Errorf("not implemented: CreateEvent - createEvent"))
}

// GetEvents is the resolver for the getEvents field.
func (r *queryResolver) GetEvents(ctx context.Context) ([]*models.Event, error) {
	events, err := dao.GetEvents(10, 0)
	fmt.Println("events: ---------->", events)
	if err != nil {
		return nil, err
	}
	var res []*models.Event
	for i := range events {
		res = append(res, &events[i])
	}
	return res, err
	// var result []*models.Event
	// if err != nil {
	// 	return nil, err
	// }
	// for i := range events {
	// 	result = append(result, &events[i])
	// }
	// return result, err
}

// GetEventByID is the resolver for the getEventById field.
func (r *queryResolver) GetEventByID(ctx context.Context, id string) (*models.Event, error) {
	panic(fmt.Errorf("not implemented: GetEventByID - getEventById"))
}

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type eventResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
