// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputGetEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int32                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputGetEvents) Reset() {
	*x = InputGetEvents{}
	mi := &file_grpc_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputGetEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputGetEvents) ProtoMessage() {}

func (x *InputGetEvents) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputGetEvents.ProtoReflect.Descriptor instead.
func (*InputGetEvents) Descriptor() ([]byte, []int) {
	return file_grpc_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *InputGetEvents) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *InputGetEvents) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_grpc_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_grpc_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_grpc_proto_events_proto protoreflect.FileDescriptor

const file_grpc_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x17grpc/proto/events.proto\x12\x06events\"D\n" +
	"\x0eInputGetEvents\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x05R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"=\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2>\n" +
	"\x06Events\x124\n" +
	"\tGetEvents\x12\x16.events.InputGetEvents\x1a\r.events.Event\"\x00B\x1dZ\x1bgithub.com/hello/grpc/protob\x06proto3"

var (
	file_grpc_proto_events_proto_rawDescOnce sync.Once
	file_grpc_proto_events_proto_rawDescData []byte
)

func file_grpc_proto_events_proto_rawDescGZIP() []byte {
	file_grpc_proto_events_proto_rawDescOnce.Do(func() {
		file_grpc_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_events_proto_rawDesc), len(file_grpc_proto_events_proto_rawDesc)))
	})
	return file_grpc_proto_events_proto_rawDescData
}

var file_grpc_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_proto_events_proto_goTypes = []any{
	(*InputGetEvents)(nil), // 0: events.InputGetEvents
	(*Event)(nil),          // 1: events.Event
}
var file_grpc_proto_events_proto_depIdxs = []int32{
	0, // 0: events.Events.GetEvents:input_type -> events.InputGetEvents
	1, // 1: events.Events.GetEvents:output_type -> events.Event
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_events_proto_init() }
func file_grpc_proto_events_proto_init() {
	if File_grpc_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_events_proto_rawDesc), len(file_grpc_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_events_proto_goTypes,
		DependencyIndexes: file_grpc_proto_events_proto_depIdxs,
		MessageInfos:      file_grpc_proto_events_proto_msgTypes,
	}.Build()
	File_grpc_proto_events_proto = out.File
	file_grpc_proto_events_proto_goTypes = nil
	file_grpc_proto_events_proto_depIdxs = nil
}
